spring.application.name=gessainvoice
spring.datasource.url=jdbc:postgresql://localhost:5432/gilustorebdd
spring.datasource.username=postgres
spring.datasource.password=root
#spring.datasource.password=$root+Iz3nshy+
#spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
server.port=8084
spring.security.user.name=admin
spring.security.user.password=1234
#swagger
springdoc.swagger-ui.path=/gessa-invoice/index.html
springdoc.swagger-ui.operationsSorter=method
# Configuracion del certificado
app.name.key=10112024-laqm_gvcax100pre
app.name.algorithm=AES/GCM/NoPadding
server.ssl.enabled=false
# configuracion sri pruebas
sri.url.RecepcionComprobantesOffline=https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl
sri.url.autorizacion=https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl
# configuracion sri produccion
#sri.url.RecepcionComprobantesOffline=https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl
#sri.url.autorizacion=https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl
#zona horaria
spring.jackson.time-zone=America/Guayaquil